### ISSUE TITLE
Major array bug

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#52]
![flintbug](https://cloud.githubusercontent.com/assets/699733/10713919/caf70f70-7a8e-11e5-9aeb-990a697aa92b.png)

**Comment by natew** [comment]
Great catch, tweaked the babel transform to wrap this better, should be fixed in the latest version.

**Comment by liron00** [comment]
Upgraded to Flint 0.2.132 and still seeing the second error.

**Comment by liron00** [comment]
This is my current workaround:
![image](https://cloud.githubusercontent.com/assets/699733/10717406/52e55e98-7b14-11e5-98ee-c8ac16bf48d9.png)

**Comment by natew** [comment]
Ah, ok pushed another build. Let me know if that worked.

**Comment by liron00** [comment]
It works thanks.
